# Dependencies
markdown:         kramdown
plugins: [jekyll-paginate]
highlighter:      rouge
future: true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               mlboyd
tagline:             'Some projects'
description:         'A compendium of some nerd projects that I actually finished' 
url:                 https://mlboyd.xyz
baseurl:             /

paginate:            5
plugins:
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap
paginate_path:      'page:num'

defaults:
  - scope:
      path: "images"
    values:
      image: true

sass:
  style: compressed

# About/contact
author:
  name:              Matthew Boyd
  url:               https://github.com/matthewlboyd
  email:             matthewlboyd@hey.com

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/matthewlboyd/mlboydxyz