# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               mlboyd.xyz
tagline:             'Some projects'
description:         'A compendium of some nerd projects that I actually finished' 
url:                 https://mlboyd.xyz
baseurl:             ''
#absolute_url:        mlboyd.xyz
paginate:            5
plugins:             [jekyll-paginate] 
paginate_path:       'page:num'

defaults:
  - scope:
      path: "images"
    values:
      image: true

sass:
  style: compressed

# About/contact
author:
  name:              Matthew Boyd
  url:               https://github.com/matthewlboyd
  email:             matthewlboyd@gmail.com

# Custom vars
version:             1.0.0

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: mlboyd-xyz